package brain3;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class LLMAdapter {
    
    public interface LLMClient {
        String complete(String prompt, String system);
    }

    public static class StubClient implements LLMClient {
        private final java.util.Map<String, String> table;

        public StubClient(java.util.Map<String, String> table) {
            this.table = table;
        }

        @Override
        public String complete(String prompt, String system) {
            String lowerPrompt = prompt.toLowerCase();
            for (java.util.Map.Entry<String, String> entry : table.entrySet()) {
                if (lowerPrompt.contains(entry.getKey().toLowerCase())) {
                    return entry.getValue();
                }
            }
            return "";
        }
    }

    public static class OllamaClient implements LLMClient {
        private final String model;
        private final String host;
        private final HttpClient client;

        public OllamaClient(String model, String host) {
            this.model = model;
            this.host = host;
            this.client = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(10))
                .build();
        }

        public OllamaClient(String model) {
            this(model, "http://localhost:11434");
        }

        @Override
        public String complete(String prompt, String system) {
            // Escape quotes and newlines for JSON
            String p = prompt.replace("\"", "\\\"").replace("\n", "\\n");
            String s = system.replace("\"", "\\\"").replace("\n", "\\n");
            
            String body = "{\"model\": \"" + model + "\", \"prompt\": \"" + p + "\", \"system\": \"" + s + "\", \"stream\": false, \"options\": {\"temperature\": 0.0}}";

            HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(host + "/api/generate"))
                .header("Content-Type", "application/json")
                .timeout(Duration.ofSeconds(180))
                .POST(HttpRequest.BodyPublishers.ofString(body))
                .build();

            try {
                HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
                String resBody = response.body();
                
                try {
                    org.json.JSONObject obj = new org.json.JSONObject(resBody);
                    if (obj.has("response")) {
                        String extracted = obj.getString("response");
                        extracted = extracted.replaceAll("<think>.*?</think>", "").trim();
                        return extracted;
                    }
                } catch (Exception e) {
                    // Fallback to empty string on parse error
                }
                return "";
            } catch (Exception e) {
                // Degrade gracefully when offline
                return "";
            }
        }
    }

    // --- BrainQL Constants ---
    public static final String EYES_SYSTEM_BQL = "You convert natural language into strict BrainQL instructions. Allowed ops: TEACH <subj> <rel> <obj>, LOOKUP <subj> <rel>, INHERIT <subj> <rel>, EXPLAIN <subj> <rel>, SOLVE <math_or_physics_problem>. Do not add quotes. Example: 'The sky is blue' -> 'TEACH sky has_color blue'. 'What is in London?' -> 'INHERIT london is_in'. 'Cats are animals' -> 'TEACH cat is_a animal'. 'Solve 2*x + 3 = 7' -> 'SOLVE 2*x + 3 = 7'. 'What is the integral of x^3?' -> 'SOLVE int x^3'. If it's just casual chat, output: CHAT <text>";
    public static final String MOUTH_SYSTEM_BQL = "You are the vocalizer for a Biological AI. You receive JSON responses from the C++ Logical BrainQL core. Convert the JSON result into natural, empathetic conversational English. CRITICAL INSTRUCTION: Read the \"known\" flag in the JSON. If \"known\" is true, assert the fact plainly. If \"known\" is false, hedge your tone as you are just musing or free-associating (e.g. 'I was just thinking about...', 'Perhaps...'). NOTE ON SCHEMA: The JSON usually represents a strict single triple (subj, rel, obj) where obj is an atomic value. However, read the \"objType\" field: if it is \"freetext\", the obj field contains a multi-word sequence of associated concepts generated by the neural predictor rather than an atomic value. Example: {\"op\": \"CHAT\", \"subj\": \"internal\", \"rel\": \"association\", \"obj\": \"dog jump fence\", \"objType\": \"freetext\", \"known\": false} -> 'I was just thinking about a dog jumping over a fence.'";

    public static class BrainQLEyes {
        private final LLMClient client;

        public BrainQLEyes(LLMClient client) {
            this.client = client;
        }

        public String parse(String text) {
            try {
                String rawBql = client.complete(text, EYES_SYSTEM_BQL).trim();
                return rawBql;
            } catch (Exception e) {
                return "";
            }
        }
    }

    public static class BrainQLMouth {
        private final LLMClient client;

        public BrainQLMouth(LLMClient client) {
            this.client = client;
        }

        public String renderResult(String resultJson) {
            try {
                String out = client.complete(resultJson, MOUTH_SYSTEM_BQL).trim();
                return out.isEmpty() ? fallbackRender(resultJson) : out;
            } catch (Exception e) {
                return fallbackRender(resultJson);
            }
        }
        
        private String fallbackRender(String resultJson) {
            return "Fallback representation: " + resultJson;
        }
    }
}
