/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class brain3_BrainNative */

#ifndef _Included_brain3_BrainNative
#define _Included_brain3_BrainNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     brain3_BrainNative
 * Method:    init
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_brain3_BrainNative_init
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     brain3_BrainNative
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    loadComponents
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_loadComponents
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     brain3_BrainNative
 * Method:    saveComponents
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_saveComponents
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     brain3_BrainNative
 * Method:    seedMathSymbols
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_seedMathSymbols
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    bindSymbol
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_bindSymbol
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     brain3_BrainNative
 * Method:    knowsSymbol
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_brain3_BrainNative_knowsSymbol
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     brain3_BrainNative
 * Method:    registerWord
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_registerWord
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     brain3_BrainNative
 * Method:    knowsWord
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_brain3_BrainNative_knowsWord
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     brain3_BrainNative
 * Method:    encodeWord
 * Signature: (JLjava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_brain3_BrainNative_encodeWord
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     brain3_BrainNative
 * Method:    bestWord
 * Signature: (J[F)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_brain3_BrainNative_bestWord
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     brain3_BrainNative
 * Method:    getEmotionArousal
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_brain3_BrainNative_getEmotionArousal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    getEmotionValence
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_brain3_BrainNative_getEmotionValence
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    getSelfMeanRecentError
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_brain3_BrainNative_getSelfMeanRecentError
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    getLastEpisode
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_brain3_BrainNative_getLastEpisode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    commitEpisode
 * Signature: (JF[F)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_commitEpisode
  (JNIEnv *, jobject, jlong, jfloat, jfloatArray);

/*
 * Class:     brain3_BrainNative
 * Method:    bindingQueryAll
 * Signature: (J[FF)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_brain3_BrainNative_bindingQueryAll
  (JNIEnv *, jobject, jlong, jfloatArray, jfloat);

/*
 * Class:     brain3_BrainNative
 * Method:    bindingBind
 * Signature: (J[F[F[F)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_bindingBind
  (JNIEnv *, jobject, jlong, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     brain3_BrainNative
 * Method:    scratchpadClear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_scratchpadClear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    scratchpadWrite
 * Signature: (JLjava/lang/String;[FLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_scratchpadWrite
  (JNIEnv *, jobject, jlong, jstring, jfloatArray, jstring);

/*
 * Class:     brain3_BrainNative
 * Method:    scratchpadRead
 * Signature: (JLjava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_brain3_BrainNative_scratchpadRead
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     brain3_BrainNative
 * Method:    startReasoning
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_startReasoning
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    forceReasonStep
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_forceReasonStep
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     brain3_BrainNative
 * Method:    executeBrainQL
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_brain3_BrainNative_executeBrainQL
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     brain3_BrainNative
 * Method:    getSpokenWords
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_brain3_BrainNative_getSpokenWords
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    clearSpokenWords
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_clearSpokenWords
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    proceduresRetrieve
 * Signature: (J[F)[I
 */
JNIEXPORT jintArray JNICALL Java_brain3_BrainNative_proceduresRetrieve
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     brain3_BrainNative
 * Method:    workingMemGate
 * Signature: (J[FF)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_workingMemGate
  (JNIEnv *, jobject, jlong, jfloatArray, jfloat);

/*
 * Class:     brain3_BrainNative
 * Method:    workingMemTick
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_workingMemTick
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    workingMemContext
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_brain3_BrainNative_workingMemContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    somActivationMap
 * Signature: (J[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_brain3_BrainNative_somActivationMap
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     brain3_BrainNative
 * Method:    daydream
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_daydream
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    sleep
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_brain3_BrainNative_sleep
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     brain3_BrainNative
 * Method:    perceive
 * Signature: (J[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_brain3_BrainNative_perceive
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     brain3_BrainNative
 * Method:    getLastConfidence
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_brain3_BrainNative_getLastConfidence
  (JNIEnv *, jobject, jlong);

/*
 * Class:     brain3_BrainNative
 * Method:    resetSequence
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_brain3_BrainNative_resetSequence
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
