#!/usr/bin/env python3
"""
brain3/tests/test_agentic_ecommerce_app.py

VERIFICATION SUITE FOR THE BRAIN'S AUTONOMOUSLY SYNTHESIZED E-COMMERCE APP:
Verifies that all 5 files generated by The Brain are valid, structured, non-empty,
and properly integrated.
"""

import unittest
import os
import sys

class TestAgenticEcommerceApp(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.workspace_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
        cls.project_dir = os.path.join(cls.workspace_dir, "ecommerce_app")

    def test_01_all_files_exist_and_non_empty(self):
        expected_files = ["index.html", "styles.css", "products.js", "particles.js", "app.js"]
        for f in expected_files:
            path = os.path.join(self.project_dir, f)
            self.assertTrue(os.path.exists(path), f"File {f} must exist")
            size = os.path.getsize(path)
            self.assertGreater(size, 500, f"File {f} must have non-trivial size (got {size} bytes)")

    def test_02_products_database_validity(self):
        path = os.path.join(self.project_dir, "products.js")
        with open(path, "r", encoding="utf-8") as fh:
            content = fh.read()
        self.assertIn("const PRODUCTS = [", content)
        self.assertIn("synapse-v4", content)
        self.assertIn("q-core-ultra", content)
        self.assertIn("cyber-retina", content)
        self.assertIn("priceUSD", content)

    def test_03_html_markup_structure(self):
        path = os.path.join(self.project_dir, "index.html")
        with open(path, "r", encoding="utf-8") as fh:
            content = fh.read()
        self.assertIn("NEURA", content)
        self.assertIn("particle-canvas", content)
        self.assertIn("cart-drawer", content)
        self.assertIn("quickview-modal", content)
        self.assertIn("checkout-modal", content)

    def test_04_css_design_system(self):
        path = os.path.join(self.project_dir, "styles.css")
        with open(path, "r", encoding="utf-8") as fh:
            content = fh.read()
        self.assertIn("--bg-primary:", content)
        self.assertIn("--accent-cyan:", content)
        self.assertIn("backdrop-filter:", content)
        self.assertIn(".product-card", content)

if __name__ == "__main__":
    unittest.main()
